// We need to work around Step numbers here if we are going to potentially exclude the AMI subscription
=== Sign in to your AWS account

. Sign in to your AWS account at https://aws.amazon.com with an IAM user role that has the necessary permissions. For details, see link:#_planning_the_deployment[Planning the deployment] earlier in this guide.
. Make sure that your AWS account is configured correctly, as discussed in the link:#_technical_requirements[Technical requirements] section.

// Optional based on Marketplace listing. Not to be edited
ifdef::marketplace_subscription[]
=== Subscribe to the {partner-product-name} AMI

This Quick Start requires a subscription to the AMI for {partner-product-name} in AWS Marketplace.

. Sign in to your AWS account.
. {marketplace_listing_url}[Open the page for the {partner-product-name} AMI in AWS Marketplace], and then choose *Continue to Subscribe*.
. Review the terms and conditions for software usage, and then choose *Accept Terms*. +
  A confirmation page loads, and an email confirmation is sent to the account owner. For detailed subscription instructions, see the https://aws.amazon.com/marketplace/help/200799470[AWS Marketplace documentation^].

. When the subscription process is complete, exit out of AWS Marketplace without further action. *Do not* provision the software from AWS Marketplace—the Quick Start deploys the AMI for you.
endif::marketplace_subscription[]
// \Not to be edited

=== Launch the Quick Start

Each deployment takes about {deployment_time} to complete.

. Sign in to your AWS account, and choose one of the following options to launch the AWS CloudFormation template. For help with choosing an option, see link:#_deployment_options[Deployment options] earlier in this guide. There are two options for asset data modeling:

.. *Option 1 - Asset Model Converter* The Asset model converter converts tag definitions and source data models from edge devices into AWS IoT SiteWise models.
+
[cols="3,1"]
|===
^|https://fwd.aws/8QYNd[Deploy {partner-product-name} into a new VPC on AWS^]
^|https://fwd.aws/WqBVa[View template^]

^|https://fwd.aws/rYGxm[Deploy {partner-product-name} into an existing VPC on AWS^]
^|https://fwd.aws/6QEKM[View template^]
|===
+
[start=2]
.. *Option 2 - Element Unify* Element Unify aligns IT and operational technology (OT) around contextualized industrial IoT data, delivering key enterprise integration and governance capabilities to industrials. By integrating previously siloed and critical time-series metadata generated by sensors across industrial operations with established IT systems, such as Enterprise Asset Management, IT and OT teams can easily work together using context data for their entire industrial IoT environment benefitting from Unify’s “contextualize once, compute anywhere, consume everywhere” approach.
+
Element Unify uses a no code/low code approach to model building using metadata from input sources such as PTC KepServerEX, Ignition from Inductive Automation, P&IDs, and PI Asset Framework from AVEVA, and feed models to AWS IoT SiteWise. Unify is suitable for single site deployments and for organizations looking to establish a solid foundation for their operational data infrastructure with a view to roll out across multiple regions and sites.
+
Fully integrated with the AWS Integrated Machine Connectivity (IMC) kit, Unify enables you to:
+
* Easily extend SiteWise to multiple edge source systems
* Improve time to insight, traceability, and data usage
* Keep SiteWise up to date (‘evergreening’)
+
Learn more about the https://www.elementanalytics.com/solutions/element-unify-for-aws[Element Unify for AWS] or check it out on the https://aws.amazon.com/marketplace/pp/prodview-trvx6gn4vqeok[AWS Marketplace].
+
[cols="3,1"]
|===
^|https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/create/review?stackName=aws-imc-unify&templateURL=https://imc-unify-demo.s3.amazonaws.com/unify-quickstart-aws-imc-integration/templates/IMC-main.template.yaml&param_ModelingVendorType=Element%20Unify&param_VPCCIDR=10.0.0.0/16&param_EdgeDeviceID=Virtual&param_PublicSubnet1CIDR=10.0.128.0/20&param_VPCTenancy=default&param_UnifyHostname=https://app001-aws.elementanalytics.com/&param_UnifyOrgId=0&param_DeploymentType=Virtual&param_AMCDriver=Element%20Unify&param_GreengrassInstanceType=t3.small&param_IgnitionInstanceType=t3.large&param_QSS3BucketRegion=us-east-1&param_DeploymentOption=Option1&param_IgnitionPrefix1=Baytown-Primary&param_IgnitionPrefix2=Houston-Secondary[Deploy Industrial Machine Connectivity with Element Unify into a new VPC on AWS^]
^|https://imc-unify-demo.s3.amazonaws.com/unify-quickstart-aws-imc-integration/templates/IMC-main.template.yaml[View template^]
|===

[start=2]
. Check the AWS Region that's displayed in the upper-right corner of the navigation bar, and change it if necessary. This Region is where the network infrastructure for {partner-product-name} is built. The template is launched in the {default_deployment_region} Region by default. For other choices, see link:#_supported_regions[Supported Regions] earlier in this guide. 

[start=3]
. On the *Create stack* page, keep the default setting for the template URL, and then choose *Next*.
. On the *Specify stack details* page, change the stack name if needed. Review the parameters for the template. Provide values for the parameters that require input. For all other parameters, review the default settings and customize them as necessary. For details on each parameter, see the link:#_parameter_reference[Parameter reference] section of this guide. When you finish reviewing and customizing the parameters, choose *Next*.