// This doc is for the "Post-deployment steps" section
// Current URL: https://aws-quickstart.github.io/quickstart-aws-industrial-machine-connectivity/#_post_deployment_steps

//TODO Shivansh, It doesn't work any more to bounce customers between post-deployment steps documented in two places, especially since the README is not being updated. I recommend that you do the following: (1) Update the post-deployment steps in the old README (eliminating references to dataflow 2a and 2b, adding Element Unify, etc.). (2) Incorporate the updated steps into this section of the guide, avoiding redundancy. (3) Replace the README content with a pointer to the guide in case anyone goes to the old README URL.
// Shivansh - The post deployment steps are more of a customization steps and not deployment steps. It's mostly used for training and enablement. That's why we decided to keep it out of deployment guide. 

After the CloudFormation stack is completed, follow the https://github.com/aws-quickstart/quickstart-aws-industrial-machine-connectivity/blob/main/assets/readme/post-deployment.md[post-deployment steps^] to configure the IMC Quick Start to make it operational.

//TODO Shivansh, After you've incorporated the README content into this section, delete the above pointer to the README.


=== Clean up the AWS CloudFormation stack deployment

Follow these steps to clean up the Quick Start AWS CloudFormation stack deployment.

==== Clean up cloud assets

. Open the AWS CloudFormation console, and delete the base stack (not the stack named *NESTED*) to clean up the account. If stack deletion fails due to nonempty S3 buckets or a deployed AWS IoT Greengrass group (for all virtual options by default, and for all physical deployments that have been completed on a piece of hardware), follow the steps below.
. Empty the S3 buckets.
.. Sign in to the AWS Management Console, and open the Amazon S3 service.
.. In the search bar, enter your stack name.
.. For each bucket that is associated with the stack, choose the bucket, and choose *Empty* under the search bar. This is the bucket-naming convention (replacing the bracketed elements): 

 `<name_of_stack>-<bucket_identifier>-<unique hash>`
+
Following are the values for <bucket_identifiers> for each deployment:
+
* amcincomingresource
* amcoutputresource
* devicesbucketresource
* imcs3bucket
* lambdazipsbucket
. Force a reset of the AWS IoT Greengrass group.
.. Open the AWS IoT Greengrass console.
.. Choose the AWS IoT Greengrass group with the *EdgeDeviceID* parameter provided to the stack.
.. Under *Actions*, choose *Reset Deployments*.
.. Select the check box indicating that you want to force the reset.
.. Choose *Reset Deployment*.
. Navigate back to the AWS CloudFormation console, and again delete the base stack—the main stack (the one that does not have *NESTED* in a gray box associated with it).
. (Optional) Clean up other resources, such as AWS IoT SiteWise portal, gateway, models, and assets as well as the QuickSight dataset.

==== Clean up edge hardware

. Navigate to a terminal on the edge hardware. Run the `sudo su` command to become the root user.
. Stop and remove Ignition from hardware as follows, replacing the information in brackets. (Not applicable for physical brownfield deployments.)

 cd /<path_to_Ignition_download>/Ignition-AWS-Kit-MQTT-v4
 ./remove.sh
 cd ..
 rm device.tar.gz group.tar.gz opcclient.der Ignition-AWS-Kit-MQTT-v4.zip physical-greenfield-option<insert_option_here>.sh
 rm -rf Ignition-AWS-Kit-MQTT-v4 

. Stop and remove AWS IoT Greengrass:

 apt remove aws-iot-greengrass-core 
 rm -rf /greengrass
 rm -rf /var/sitewise